### PR TITLE
Handle changes to authentication process introduced in 1_27

### PR DESCRIPTION
**Pull request by rockclimb**
I'd appreciate thoughts on this patch - happy to modify if required.

### CODE REVIEW

**Comment by benjaoming** [comment]
Sorry that I took some time to test this.

It works like a charm!

1) CreateAccount now works when following link from invite email
2) CreateAccount does is still correctly denying access to other users not presenting a valid `invite` token

**Comment by lmannering** [comment]
Has there been any update on merging this please? Thanks

**Comment by benjaoming** [comment]
LGTM!

**Comment by GPhilo** [comment]
Pinging this, the problem seem to still be there with MediaWiki version 1.29.1

**Comment by tomschulze** [comment]
I am using this extension successfully after implementing the modifications from this PR. I use Mediawiki 1.32 alpha. However, I did face the 'Account creation error', after having installed PermissionsACL. The extension was overriding the permission settings (either the access of the Special:AccountCreation page or the right to create an account; not sure). Disabling it solved the issue. So it might be worth it checking for extensions modifying user rights/permissions.

**Comment by rockclimb** [comment]
This has been resolved by commit a1c431f09df84a434949f596d79e0891d5bd5acf today.

**Pull request closed without merging**
